name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -o get-poetry.py
          python get-poetry.py
          source $HOME/.poetry/env
          poetry config virtualenvs.in-project true
      - name: Build docker image
        run: |
          poetry install --dev
      - name: Build docker image
        run: |
          poetry run flake8 src tests
      - name: Build docker image
        run: |
          poetry run flake8 src tests
