name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    env:
      SHA: ${{ github.sha }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Get poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Load cache
        id: valid-cache
        uses: actions/cache@v2
        with:
          key: ${{ matrix.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
          path: |
            ${{ github.workspace }}/.venv
      - name: Install dependencies
        if: steps.valid-cache.outputs.cache-hit != 'true'
        run: |
          python3 -m venv .venv
          poetry install
      - name: Running flake8
        run: |
          poetry run flake8 src tests
      - name: Running black
        run: |
          poetry run black --check src tests
      - name: Running isort
        run: |
          poetry run isort --check --recursive src tests
      - name: Running tests and coverage
        run: |
          poetry run pytest -v --cov-report=xml --cov=logicipi
      - name: Send coverage
        run:
          poetry run coveralls
